---
# tasks file for ansible-role-docker-container-stirlingpdf

- name: docker_image pull {{ docker_image_stirlingpdf_name }}
  community.docker.docker_image:
    name: '{{ docker_image_stirlingpdf_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_stirlingpdf_pull

- name: docker_network {{ docker_container_stirlingpdf_name }}
  community.docker.docker_network:
    name: "{{ docker_network_stirlingpdf_name }}"
    driver: "{{ docker_network_stirlingpdf_driver | default('bridge') }}"
    attachable: "{{ docker_network_stirlingpdf_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_stirlingpdf_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_stirlingpdf_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_stirlingpdf_name }}
  community.docker.docker_container:
    name: "{{ docker_container_stirlingpdf_name }}"
    comparisons: "{{ docker_container_stirlingpdf_comparisons }}"
    image: "{{ docker_container_stirlingpdf_image }}"
    state: "{{ docker_container_stirlingpdf_state | default('started') }}"
    recreate: "{{ docker_container_stirlingpdf_recreate | default(false) }}"
    restart: "{{ docker_container_stirlingpdf_restart | default(false) }}"
    restart_policy: "{{ docker_container_stirlingpdf_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_stirlingpdf_auto_remove | default(false) }}"
    detach: "{{ docker_container_stirlingpdf_detach | default(true) }}"
    init: "{{ docker_container_stirlingpdf_init | default(false) }}"
    interactive: "{{ docker_container_stirlingpdf_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_stirlingpdf_keep_volumes | default(true) }}"
    memory: "{{ docker_container_stirlingpdf_memory | default('0') }}"
    paused: "{{ docker_container_stirlingpdf_paused | default(false) }}"
    privileged: "{{ docker_container_stirlingpdf_privileged | default(false) }}"
    read_only: "{{ docker_container_stirlingpdf_read_only | default(false) }}"
    tty: "{{ docker_container_stirlingpdf_tty | default(false) }}"
    env_file: "{{ docker_container_stirlingpdf_env_file | default(omit) }}"
    env: "{{ docker_container_stirlingpdf_env | default(omit) }}"
    volumes: "{{ docker_container_stirlingpdf_volumes | default(omit) }}"
    labels: "{{ docker_container_stirlingpdf_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_stirlingpdf_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_stirlingpdf_name }}"
    pull: "{{ docker_container_stirlingpdf_pull | default(false) }}"
    networks: "{{ docker_container_stirlingpdf_networks }}"
    published_ports: "{{ docker_container_stirlingpdf_ports | default(omit) }}"

- name: docker_container - {{ docker_container_stirlingpdf_volume_dir }} download  additional ocr
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ docker_container_stirlingpdf_volume_dir }}/tessdata/"
  loop: "{{ docker_container_stirlingpdf_tessdata_language_pack_urls }}"
  when:
    - docker_container_stirlingpdf_tessdata_language_pack_urls is defined
    - docker_container_stirlingpdf_tessdata_language_pack_urls | length > 0
...
